# Generated by Django 3.0.6 on 2020-06-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200602_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rez',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='rez',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='rel_payment_rez', to='api.rez'),
            preserve_default=False,
        ),
    ]
