# Generated by Django 3.0.6 on 2020-06-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200606_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rez',
            name='confirmationNumber',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='rez',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_rez_user', to='api.user'),
        ),
    ]
