# Generated by Django 3.0.6 on 2020-07-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200626_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='doneTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rez', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_task_rez', to='api.rez')),
            ],
        ),
    ]
