# Generated by Django 3.0.6 on 2020-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_donetasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='donetasks',
            name='message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
